export const paidGames = [
    {
      poster: require('../assets/images/list/spiderman.png'),
      title: 'Spider-Man',
      subtitle: 'Marvel',
      isFree: 'No',
      price: '$25.99',
      id: '1',
    },
    {
      poster: require('../assets/images/list/battlefield-2042.webp'),
      title: 'Battlefield 2042',
      subtitle: 'EA',
      isFree: 'No',
      price: '$19.99',
      id: '2',
    },
    {
      poster: require('../assets/images/list/miles-morales.webp'),
      title: 'Spider-Man: Miles Morales',
      subtitle: 'Marvel',
      isFree: 'No',
      price: '$29.99',
      id: '3',
    },
    {
      poster: require('../assets/images/list/halo-infinite.jpeg'),
      title: 'Halo Infinite',
      subtitle: 'Xbox Game',
      isFree: 'No',
      price: '$24.99',
      id: '4',
    },
    {
      poster: require('../assets/images/list/FarCry6.png'),
      title: 'Far Cry 6',
      subtitle: 'Ubisoft',
      isFree: 'No',
      price: '$15.99',
      id: '5',
    },
    {
      poster: require('../assets/images/list/god-of-war.jpeg'),
      title: 'God of War: Ragnarok',
      subtitle: 'Sony',
      isFree: 'No',
      price: '$25.99',
      id: '6',
    },
  ];
  
  export const freeGames = [
    {
      poster: require('../assets/images/list/Altos-Odyssey.jpeg'),
      title: 'Altos Odyssey',
      subtitle: 'Noodlecake Studios',
      isFree: 'Yes',
      id: '1',
    },
    {
      poster: require('../assets/images/list/asphalt-9.jpeg'),
      title: 'Asphalt 9',
      subtitle: 'Gameloft',
      isFree: 'Yes',
      id: '2',
    },
    {
      poster: require('../assets/images/list/genshin-impact.jpeg'),
      title: 'Genshin Impact',
      subtitle: 'miHoYo',
      isFree: 'Yes',
      id: '3',
    },
    {
      poster: require('../assets/images/list/fortnite.webp'),
      title: 'Fortnite',
      subtitle: 'Epic Games',
      isFree: 'Yes',
      id: '4',
    },
    {
      poster: require('../assets/images/list/pokemon-unite.jpeg'),
      title: 'Pokémon Unite',
      subtitle: 'The Pokémon Company',
      isFree: 'Yes',
      id: '5',
    },
    {
      poster: require('../assets/images/list/diablo-4.jpeg'),
      title: 'Diablo 4',
      subtitle: 'Blizzard Entertainment',
      isFree: 'No',
      id: '6',
    },
  ];